// converstation list
export const conversations = [
  {
    id: 1,
    storeName: "Rahim Fashion",
    sellerName: "Rahim Ahmed",
    avatar: "http://localhost:5173/src/assets/profile_placeholder.png",
    lastMessage: "Can you check my payment?",
    time: "2m",
    unread: 3,
    online: true,
  },
  {
    id: 2,
    storeName: "Tech World",
    sellerName: "Karim Hasan",
    avatar: "http://localhost:5173/src/assets/profile_placeholder.png",
    lastMessage: "Thank you admin.",
    time: "15m",
    unread: 0,
    online: true,
  },
  {
    id: 3,
    storeName: "Urban Mart",
    sellerName: "Hasan Ali",
    avatar: "https://i.pravatar.cc/100?img=14",
    lastMessage: "I need help with an order.",
    time: "1h",
    unread: 5,
    online: false,
  },
  {
    id: 4,
    storeName: "Smart Gadgets",
    sellerName: "Noman Khan",
    avatar: "https://i.pravatar.cc/100?img=15",
    lastMessage: "Product approval issue.",
    time: "2h",
    unread: 0,
    online: false,
  },

  {
    id: 5,
    storeName: "Smart Gadgets",
    sellerName: "Noman Khan",
    avatar: "https://i.pravatar.cc/100?img=15",
    lastMessage: "Product approval issue.",
    time: "2h",
    unread: 6,
    online: false,
  },

  {
    id: 6,
    storeName: "Smart Gadgets",
    sellerName: "Noman Khan",
    avatar: "https://i.pravatar.cc/100?img=15",
    lastMessage: "Product approval issue.",
    time: "2h",
    unread: 2,
    online: false,
  },

  {
    id: 7,
    storeName: "Smart Gadgets",
    sellerName: "Noman Khan",
    avatar: "https://i.pravatar.cc/100?img=15",
    lastMessage: "Product approval issue.",
    time: "2h",
    unread: 0,
    online: false,
  },
  {
    id: 8,
    storeName: "Smart Gadgets",
    sellerName: "Noman Khan",
    avatar: "https://i.pravatar.cc/100?img=15",
    lastMessage: "Product approval issue.",
    time: "2h",
    unread: 0,
    online: false,
  },
  {
    id: 9,
    storeName: "Smart Gadgets",
    sellerName: "Noman Khan",
    avatar: "https://i.pravatar.cc/100?img=15",
    lastMessage: "Product approval issue.",
    time: "2h",
    unread: 0,
    online: false,
  },
];

// message list
export const messages = [
  // Conversation 1: Payment Issue
  {
    id: 1,
    sender: "seller",
    text: "Hello Admin, I have a problem with my payment request. Hello Admin, I have a problem with my payment request. Hello Admin, I have a problem with my payment request. Hello Admin, I have a problem with my payment request. Hello Admin, I have a problem with my payment request. Hello Admin, I have a problem with my payment request. Hello Admin, I have a problem with my payment request. Hello Admin, I have a problem with my payment request. Hello Admin, I have a problem with my payment request.",
    time: "10:41 AM",
  },
  {
    id: 2,
    sender: "admin",
    text: "Hello Rahim. Sure, let me check that for you.",
    time: "10:42 AM",
    seen: true,
  },
  {
    id: 3,
    sender: "seller",
    text: "The withdrawal request has been pending since yesterday.",
    time: "10:43 AM",
  },
  {
    id: 4,
    sender: "admin",
    text: "I checked your account. The payment is currently under review.",
    time: "10:44 AM",
    seen: true,
  },
  {
    id: 5,
    sender: "seller",
    text: "Okay. How long will the review take?",
    time: "10:45 AM",
  },
  {
    id: 6,
    sender: "admin",
    text: "It usually takes 24-48 hours. Please be patient.",
    time: "10:46 AM",
    seen: true,
  },
  { id: 7, sender: "seller", text: "Understood. Thank you.", time: "10:47 AM" },
  {
    id: 8,
    sender: "admin",
    text: "You're welcome. Anything else I can help with?",
    time: "10:48 AM",
    seen: true,
  },
  {
    id: 9,
    sender: "seller",
    text: "No, that will be all for now.",
    time: "10:50 AM",
  },
  {
    id: 10,
    sender: "admin",
    text: "Great! Have a good day.",
    time: "10:51 AM",
    seen: true,
  },

  // Conversation 2: Product Approval
  {
    id: 11,
    sender: "seller",
    text: "Hi, my recent product uploads are still pending.",
    time: "11:05 AM",
  },
  {
    id: 12,
    sender: "admin",
    text: "Hello! Let me pull up your store ID.",
    time: "11:06 AM",
    seen: true,
  },
  {
    id: 13,
    sender: "seller",
    text: "My store ID is #SL1024.",
    time: "11:07 AM",
  },
  {
    id: 14,
    sender: "admin",
    text: "Thanks. I see 5 products waiting for approval.",
    time: "11:09 AM",
    seen: true,
  },
  {
    id: 15,
    sender: "seller",
    text: "Yes, mostly electronics and accessories.",
    time: "11:10 AM",
  },
  {
    id: 16,
    sender: "admin",
    text: "The images for the smartwatches are a bit blurry.",
    time: "11:12 AM",
    seen: true,
  },
  {
    id: 17,
    sender: "seller",
    text: "Oh, should I re-upload them?",
    time: "11:13 AM",
  },
  {
    id: 18,
    sender: "admin",
    text: "Yes, please use high-resolution images (minimum 800x800).",
    time: "11:15 AM",
    seen: true,
  },
  {
    id: 19,
    sender: "seller",
    text: "Will do. Approving the rest?",
    time: "11:16 AM",
  },
  {
    id: 20,
    sender: "admin",
    text: "I have approved the other 4 items. They are live now.",
    time: "11:18 AM",
    seen: true,
  },

  // Conversation 3: Customer Refund Dispute
  {
    id: 21,
    sender: "seller",
    text: "Admin, order #ORD-10231 requested a refund unfairly.",
    time: "12:00 PM",
  },
  {
    id: 22,
    sender: "admin",
    text: "Hello. What is the reason the customer stated?",
    time: "12:05 PM",
    seen: true,
  },
  {
    id: 23,
    sender: "seller",
    text: "They said the item was damaged, but I packed it perfectly.",
    time: "12:06 PM",
  },
  {
    id: 24,
    sender: "admin",
    text: "Did you take a video during packaging?",
    time: "12:08 PM",
    seen: true,
  },
  {
    id: 25,
    sender: "seller",
    text: "Yes, I have the CCTV footage.",
    time: "12:10 PM",
  },
  {
    id: 26,
    sender: "admin",
    text: "Please send the video to disputes@ourmarketplace.com.",
    time: "12:12 PM",
    seen: true,
  },
  {
    id: 27,
    sender: "seller",
    text: "Just emailed it. Please check.",
    time: "12:15 PM",
  },
  {
    id: 28,
    sender: "admin",
    text: "Received. Our team will review it within 24 hours.",
    time: "12:20 PM",
    seen: true,
  },
  {
    id: 29,
    sender: "seller",
    text: "Will the amount be deducted from my wallet?",
    time: "12:22 PM",
  },
  {
    id: 30,
    sender: "admin",
    text: "Not until the investigation is complete. It is currently on hold.",
    time: "12:25 PM",
    seen: true,
  },

  // Conversation 4: Technical Bug / Dashboard Issue
  {
    id: 31,
    sender: "seller",
    text: "My dashboard is showing zero sales for today, which is incorrect.",
    time: "01:10 PM",
  },
  {
    id: 32,
    sender: "admin",
    text: "Hi there. We are currently facing a sync delay.",
    time: "01:12 PM",
    seen: true,
  },
  {
    id: 33,
    sender: "seller",
    text: "How long will this take to fix?",
    time: "01:13 PM",
  },
  {
    id: 34,
    sender: "admin",
    text: "Our engineers are on it. Estimated resolution is 1 hour.",
    time: "01:15 PM",
    seen: true,
  },
  {
    id: 35,
    sender: "seller",
    text: "I got an order notification but it's not in the 'Pending' list.",
    time: "01:17 PM",
  },
  {
    id: 36,
    sender: "admin",
    text: "That is part of the same cache issue. Don't worry, no data is lost.",
    time: "01:19 PM",
    seen: true,
  },
  {
    id: 37,
    sender: "seller",
    text: "Should I hold off on shipping?",
    time: "01:21 PM",
  },
  {
    id: 38,
    sender: "admin",
    text: "Yes, wait until the dashboard updates properly.",
    time: "01:22 PM",
    seen: true,
  },
  {
    id: 39,
    sender: "seller",
    text: "Okay, I'll check back in an hour.",
    time: "01:25 PM",
  },
  {
    id: 40,
    sender: "admin",
    text: "Thank you for your patience.",
    time: "01:26 PM",
    seen: true,
  },

  // Conversation 5: Account Verification
  {
    id: 41,
    sender: "seller",
    text: "I uploaded my NID for KYC verification 3 days ago.",
    time: "02:00 PM",
  },
  {
    id: 42,
    sender: "admin",
    text: "Let me check the status of your KYC.",
    time: "02:05 PM",
    seen: true,
  },
  {
    id: 43,
    sender: "seller",
    text: "It still shows 'Pending Verification'.",
    time: "02:06 PM",
  },
  {
    id: 44,
    sender: "admin",
    text: "I see the document. The back side of the NID is missing.",
    time: "02:10 PM",
    seen: true,
  },
  {
    id: 45,
    sender: "seller",
    text: "Oh, the portal only allowed one image upload.",
    time: "02:11 PM",
  },
  {
    id: 46,
    sender: "admin",
    text: "You can merge both sides into one PDF or image.",
    time: "02:12 PM",
    seen: true,
  },
  {
    id: 47,
    sender: "seller",
    text: "Okay, I will do that and re-upload.",
    time: "02:15 PM",
  },
  {
    id: 48,
    sender: "admin",
    text: "I have rejected the current one so you can upload again.",
    time: "02:16 PM",
    seen: true,
  },
  {
    id: 49,
    sender: "seller",
    text: "Done. Just uploaded the new file.",
    time: "02:20 PM",
  },
  {
    id: 50,
    sender: "admin",
    text: "Verified! Your account is now fully active.",
    time: "02:22 PM",
    seen: true,
  },

  // Conversation 6: Shipping & Logistics
  {
    id: 51,
    sender: "seller",
    text: "The delivery rider hasn't come for pickup today.",
    time: "03:30 PM",
  },
  {
    id: 52,
    sender: "admin",
    text: "Hello! Which area is your warehouse located in?",
    time: "03:32 PM",
    seen: true,
  },
  { id: 53, sender: "seller", text: "Mirpur 10, Block C.", time: "03:33 PM" },
  {
    id: 54,
    sender: "admin",
    text: "Due to heavy rain, pickups in Mirpur are delayed.",
    time: "03:35 PM",
    seen: true,
  },
  {
    id: 55,
    sender: "seller",
    text: "But I have 15 orders that need to go out today.",
    time: "03:36 PM",
  },
  {
    id: 56,
    sender: "admin",
    text: "I am assigning a priority rider. He should be there by 5 PM.",
    time: "03:40 PM",
    seen: true,
  },
  {
    id: 57,
    sender: "seller",
    text: "Can I get his phone number?",
    time: "03:41 PM",
  },
  {
    id: 58,
    sender: "admin",
    text: "Yes, his name is Shafiq. Number: 01711XXXXXX.",
    time: "03:42 PM",
    seen: true,
  },
  {
    id: 59,
    sender: "seller",
    text: "Got it. I'll call him.",
    time: "03:45 PM",
  },
  {
    id: 60,
    sender: "admin",
    text: "Let us know if he doesn't arrive by 5 PM.",
    time: "03:46 PM",
    seen: true,
  },

  // Conversation 7: Promotional Campaigns
  {
    id: 61,
    sender: "seller",
    text: "How can I join the upcoming Flash Sale?",
    time: "04:15 PM",
  },
  {
    id: 62,
    sender: "admin",
    text: "Hi! You can apply from the 'Campaigns' tab in your dashboard.",
    time: "04:17 PM",
    seen: true,
  },
  {
    id: 63,
    sender: "seller",
    text: "It says my store rating is too low.",
    time: "04:18 PM",
  },
  {
    id: 64,
    sender: "admin",
    text: "Flash sales require a minimum store rating of 4.5.",
    time: "04:20 PM",
    seen: true,
  },
  {
    id: 65,
    sender: "seller",
    text: "My current rating is 4.4.",
    time: "04:21 PM",
  },
  {
    id: 66,
    sender: "admin",
    text: "Try requesting reviews from your recent successful deliveries.",
    time: "04:23 PM",
    seen: true,
  },
  {
    id: 67,
    sender: "seller",
    text: "Is there any other campaign I can join?",
    time: "04:25 PM",
  },
  {
    id: 68,
    sender: "admin",
    text: "Yes, the 'Weekend Deals' campaign is open for 4.0+ ratings.",
    time: "04:27 PM",
    seen: true,
  },
  {
    id: 69,
    sender: "seller",
    text: "Awesome, I just registered for that one.",
    time: "04:30 PM",
  },
  {
    id: 70,
    sender: "admin",
    text: "Perfect. We will review your product discounts shortly.",
    time: "04:31 PM",
    seen: true,
  },

  // Conversation 8: Category Change Request
  {
    id: 71,
    sender: "seller",
    text: "I accidentally listed a T-shirt under 'Electronics'.",
    time: "05:00 PM",
  },
  {
    id: 72,
    sender: "admin",
    text: "Please provide the Product ID.",
    time: "05:02 PM",
    seen: true,
  },
  {
    id: 73,
    sender: "seller",
    text: "Product ID is PRD-9982.",
    time: "05:03 PM",
  },
  {
    id: 74,
    sender: "admin",
    text: "I see it. I have moved it to Men's Fashion > Clothing.",
    time: "05:05 PM",
    seen: true,
  },
  {
    id: 75,
    sender: "seller",
    text: "Thank you! Also, can I change the brand name?",
    time: "05:07 PM",
  },
  {
    id: 76,
    sender: "admin",
    text: "Brand name changes require proof of brand authorization.",
    time: "05:10 PM",
    seen: true,
  },
  {
    id: 77,
    sender: "seller",
    text: "It's my own brand. I have the trade license.",
    time: "05:12 PM",
  },
  {
    id: 78,
    sender: "admin",
    text: "Upload the trade license to the 'Documents' section.",
    time: "05:15 PM",
    seen: true,
  },
  { id: 79, sender: "seller", text: "Uploaded just now.", time: "05:20 PM" },
  {
    id: 80,
    sender: "admin",
    text: "Approved. You can now edit the brand name.",
    time: "05:22 PM",
    seen: true,
  },

  // Conversation 9: Penalty & Warnings
  {
    id: 81,
    sender: "seller",
    text: "I received a warning email about 'Delayed Shipments'.",
    time: "06:10 PM",
  },
  {
    id: 82,
    sender: "admin",
    text: "Yes, 3 of your orders breached the 48-hour SLA.",
    time: "06:12 PM",
    seen: true,
  },
  {
    id: 83,
    sender: "seller",
    text: "The stock ran out suddenly.",
    time: "06:13 PM",
  },
  {
    id: 84,
    sender: "admin",
    text: "You must keep your inventory updated to avoid penalties.",
    time: "06:15 PM",
    seen: true,
  },
  {
    id: 85,
    sender: "seller",
    text: "Will my account be suspended?",
    time: "06:17 PM",
  },
  {
    id: 86,
    sender: "admin",
    text: "Not for a first warning. But next time it will affect your visibility.",
    time: "06:20 PM",
    seen: true,
  },
  {
    id: 87,
    sender: "seller",
    text: "I have updated all stock levels now.",
    time: "06:25 PM",
  },
  {
    id: 88,
    sender: "admin",
    text: "Good. Please ensure out-of-stock items are disabled.",
    time: "06:27 PM",
    seen: true,
  },
  {
    id: 89,
    sender: "seller",
    text: "Understood. It won't happen again.",
    time: "06:30 PM",
  },
  {
    id: 90,
    sender: "admin",
    text: "Thank you for your cooperation.",
    time: "06:31 PM",
    seen: true,
  },

  // Conversation 10: Feedback and Feature Requests
  {
    id: 91,
    sender: "seller",
    text: "Is there a way to bulk-update prices using an Excel sheet?",
    time: "07:00 PM",
  },
  {
    id: 92,
    sender: "admin",
    text: "Yes! Go to Products > Import/Export in the sidebar.",
    time: "07:05 PM",
    seen: true,
  },
  {
    id: 93,
    sender: "seller",
    text: "I tried, but it gives a 'Format Error'.",
    time: "07:07 PM",
  },
  {
    id: 94,
    sender: "admin",
    text: "Make sure you are downloading our specific template first.",
    time: "07:10 PM",
    seen: true,
  },
  {
    id: 95,
    sender: "seller",
    text: "Ah, I was using my own Excel file.",
    time: "07:12 PM",
  },
  {
    id: 96,
    sender: "admin",
    text: "Download the template, fill it, and upload it as a CSV.",
    time: "07:15 PM",
    seen: true,
  },
  {
    id: 97,
    sender: "seller",
    text: "It worked perfectly! Saved me so much time.",
    time: "07:25 PM",
  },
  {
    id: 98,
    sender: "admin",
    text: "Glad to hear that!",
    time: "07:26 PM",
    seen: true,
  },
  {
    id: 99,
    sender: "seller",
    text: "You guys should add a dark mode to this dashboard.",
    time: "07:30 PM",
  },
  {
    id: 100,
    sender: "admin",
    text: "That's a great suggestion! I'll pass it to the dev team.",
    time: "07:35 PM",
    seen: true,
  },
];

// recentOrders list
export const recentOrders = [
  {
    id: "#ORD-10231",
    amount: "$120.00",
    status: "Delivered",
  },
  {
    id: "#ORD-10228",
    amount: "$85.00",
    status: "Processing",
  },
  {
    id: "#ORD-10219",
    amount: "$240.00",
    status: "Delivered",
  },
];
